# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-23 18:03
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_auto_20160423_0300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
