# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-22 22:39
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_user_club'),
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='club',
            name='fb_page',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='foundation',
            field=models.DateField(default=datetime.datetime(2016, 4, 22, 22, 38, 15, 473000, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='club',
            name='header_description',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='club',
            name='header_image',
            field=models.ImageField(default='', upload_to=b'uploads/clubs/headers/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='club',
            name='tw_page',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='website',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='yt_page',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='president',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='president', to='clubs.Partner'),
            preserve_default=False,
        ),
    ]
