# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-23 07:04
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0013_auto_20160422_1810'),
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='club',
            name='fb_page',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='club',
            name='foundation',
            field=models.DateField(default='', verbose_name='Fecha de fundaci\xf3n'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='club',
            name='header_description',
            field=models.CharField(default='', max_length=100, verbose_name='Descripci\xf3n de la imagen'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='club',
            name='header_image',
            field=models.ImageField(default='', upload_to=b'uploads/clubs/headers/', verbose_name='Imagen de perfil'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='club',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Club activo'),
        ),
        migrations.AddField(
            model_name='club',
            name='tw_page',
            field=models.URLField(blank=True, null=True, verbose_name='Twitter'),
        ),
        migrations.AddField(
            model_name='club',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Sitio web'),
        ),
        migrations.AddField(
            model_name='club',
            name='yt_page',
            field=models.URLField(blank=True, null=True, verbose_name='Youtube'),
        ),
        migrations.AlterField(
            model_name='club',
            name='logo',
            field=models.ImageField(upload_to=b'uploads/clubs/logos/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre del club'),
        ),
        migrations.AddField(
            model_name='club',
            name='president',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='president', to='clubs.Partner', verbose_name='Presidente'),
        ),
    ]
