# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-23 07:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del club')),
                ('logo', models.ImageField(upload_to=b'uploads/clubs/logos/', verbose_name='Logo')),
                ('header_image', models.ImageField(upload_to=b'uploads/clubs/headers/', verbose_name='Imagen de perfil')),
                ('header_description', models.CharField(max_length=100, verbose_name='Descripci\xf3n de la imagen')),
                ('foundation', models.DateField(verbose_name='Fecha de fundaci\xf3n')),
                ('is_active', models.BooleanField(default=True, verbose_name='Club activo')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Sitio web')),
                ('fb_page', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('tw_page', models.URLField(blank=True, null=True, verbose_name='Twitter')),
                ('yt_page', models.URLField(blank=True, null=True, verbose_name='Youtube')),
                ('president', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='president', to=settings.AUTH_USER_MODEL, verbose_name='Presidente')),
            ],
        ),
        migrations.RemoveField(
            model_name='clubs',
            name='president',
        ),
        migrations.DeleteModel(
            name='Clubs',
        ),
    ]
