# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-22 22:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_auto_20160422_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='foundation',
            field=models.DateField(default=datetime.datetime(2016, 4, 22, 22, 41, 1, 328000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='club',
            name='president',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='president', to='clubs.Partner'),
        ),
    ]
