# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-22 23:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_auto_20160422_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='foundation',
            field=models.DateField(),
        ),
    ]
