# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-22 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_auto_20160422_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='foundation',
            field=models.DateField(),
        ),
    ]
