# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-23 01:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_auto_20160422_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='fb_page',
            field=models.URLField(null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='club',
            name='foundation',
            field=models.DateField(verbose_name='Fecha de fundaci\xf3n'),
        ),
        migrations.AlterField(
            model_name='club',
            name='header_description',
            field=models.CharField(max_length=100, verbose_name='Descripci\xf3n de la imagen'),
        ),
        migrations.AlterField(
            model_name='club',
            name='header_image',
            field=models.ImageField(upload_to=b'uploads/clubs/headers/', verbose_name='Imagen de perfil'),
        ),
        migrations.AlterField(
            model_name='club',
            name='logo',
            field=models.ImageField(upload_to=b'uploads/clubs/logos/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre del club'),
        ),
        migrations.AlterField(
            model_name='club',
            name='president',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='president', to='clubs.Partner', verbose_name='Presidente'),
        ),
        migrations.AlterField(
            model_name='club',
            name='tw_page',
            field=models.URLField(null=True, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='club',
            name='website',
            field=models.URLField(null=True, verbose_name='Sitio web'),
        ),
        migrations.AlterField(
            model_name='club',
            name='yt_page',
            field=models.URLField(null=True, verbose_name='Youtube'),
        ),
    ]
