# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-23 02:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_auto_20160422_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='president',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='president', to='clubs.Partner', verbose_name='Presidente'),
        ),
    ]
