# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-23 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0008_auto_20160422_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='fb_page',
            field=models.URLField(verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='club',
            name='tw_page',
            field=models.URLField(verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='club',
            name='website',
            field=models.URLField(verbose_name='Sitio web'),
        ),
        migrations.AlterField(
            model_name='club',
            name='yt_page',
            field=models.URLField(verbose_name='Youtube'),
        ),
    ]
