# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-23 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0010_auto_20160423_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Club activo'),
        ),
    ]
